"""CRUD operations to populate mocking bird database."""

from model import db, connect_to_db, User, Generated_Text, Sample_Text , Sample_Text_Source

# TODO: deploy o-auth using facebook for login/user profile
# TODO:finish user generation
def create_user(email, password, name):
    """Create and return a new user."""

    user = User(email=email, password=password, name=name)
    
    # Note: Add to the session or it won't be stored
    db.session.add(user)
    db.session.commit()
    
    return user

def add_generated_text():
    """adds text generated by the users to the database"""

    # ? should I get generated text from the backend when it's generated or front end when it's displayed??
    generated_text = ()

    db.session.add(generated_text)
    db.session.commit()

    return 

# ? Flesh out getting tweets function - get tweets by user, get tweets by date, get tweets by source?
# TODO: Implement get tweets function
# def get_tweets():
#     """Gets all regenerated tweets in the database."""
    
#     return __blank__.query.all()


if __name__ == '__main__':
    from server import app
    connect_to_db(app)